"""
    datagenerate(d, K, N; path=nothing, seed=nothing) -> Dict{String, Any}

Generate synthetic memory-pattern datasets for stochastic attention experiments.

Each dataset is a `d × K` matrix `X` whose columns are i.i.d. draws from the 
uniform distribution on the unit sphere ``\\mathbb{S}^{d-1}``. Patterns are 
generated by sampling ``\\mathbf{x}_k \\sim \\mathcal{N}(\\mathbf{0}, \\mathbf{I}_d)`` 
and normalizing ``\\mathbf{x}_k \\leftarrow \\mathbf{x}_k / \\|\\mathbf{x}_k\\|``.
This is the standard setup in the Hopfield capacity literature.

# Arguments
- `d::Int`: Pattern dimensionality (number of rows in each memory matrix).
- `K::Int`: Number of stored patterns (number of columns in each memory matrix).
- `N::Int`: Number of independent datasets to generate.

# Keyword Arguments
- `path::Union{String, Nothing}=nothing`: Directory in which to save datasets. 
  If `nothing`, datasets are returned in memory but not saved. When a path is 
  provided, a single `data.jld2` file is written containing all datasets and 
  metadata, plus individual `patterns_i.csv` files for portability.
- `seed::Union{Int, Nothing}=nothing`: Random seed for reproducibility. If `nothing`, 
  the global RNG state is used unchanged. When provided, `Random.seed!(seed)` is 
  called before generation so that results are exactly reproducible.

# Returns
A `Dict{String, Any}` with the following keys:
- `"datasets"`: A `Vector{Matrix{Float64}}` of length `N`, where each element is a 
  `d × K` matrix of unit-norm patterns.
- `"d"`: The pattern dimensionality.
- `"K"`: The number of stored patterns per dataset.
- `"N"`: The number of datasets generated.
- `"load_ratio"`: The load ratio `K / d`.
- `"seed"`: The seed used (or `nothing`).
- `"path"`: The output directory (or `nothing`).
- `"timestamp"`: ISO 8601 timestamp of generation.
- `"julia_version"`: Julia version string used for generation.

# Saved files (when `path` is provided)
- `data.jld2`: JLD2 archive containing the full return `Dict` (load with 
  `JLD2.load("data.jld2", "result")`).
- `patterns_i.csv` for `i = 1, …, N`: Individual CSV files for portability 
  (rows = dimensions, columns = patterns).

# Examples
```julia
# Generate 5 datasets of 16 patterns in 64 dimensions (in memory only)
result = datagenerate(64, 16, 5)
X1 = result["datasets"][1]  # 64 × 16 matrix, each column has unit norm

# Generate and save to disk (JLD2 + CSV)
result = datagenerate(64, 16, 5; path="data/synthetic", seed=42)

# Reload later
using JLD2
result = JLD2.load("data/synthetic/data.jld2", "result")
```
"""
function datagenerate(d::Int, K::Int, N::Int;
    path::Union{String, Nothing} = nothing,
    seed::Union{Int, Nothing} = nothing)::Dict{String, Any}

    # validate inputs
    d > 0 || throw(ArgumentError("d must be positive, got d = $d"))
    K > 0 || throw(ArgumentError("K must be positive, got K = $K"))
    N > 0 || throw(ArgumentError("N must be positive, got N = $N"))

    # set seed if provided
    if seed !== nothing
        Random.seed!(seed)
    end

    # generate N datasets
    datasets = Vector{Matrix{Float64}}(undef, N)
    for i in 1:N
        X = randn(d, K)                    # d × K, entries ~ N(0,1)
        for k in 1:K
            X[:, k] ./= norm(X[:, k])      # normalize each column to the unit sphere
        end
        datasets[i] = X
    end

    # build result dict with metadata
    result = Dict{String, Any}(
        "datasets"      => datasets,
        "d"             => d,
        "K"             => K,
        "N"             => N,
        "load_ratio"    => K / d,
        "seed"          => seed,
        "path"          => path,
        "timestamp"     => Dates.format(Dates.now(), "yyyy-mm-ddTHH:MM:SS"),
        "julia_version" => string(VERSION)
    )

    # save to disk if path is provided
    if path !== nothing
        mkpath(path)

        # JLD2: single archive with everything
        jld2file = joinpath(path, "data.jld2")
        JLD2.save(jld2file, "result", result)

        # CSV: individual files for portability
        for i in 1:N
            filename = joinpath(path, "patterns_$i.csv")
            CSV.write(filename, DataFrame(datasets[i], :auto))
        end
    end

    return result
end
